name: Tests

on: pull_request

jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - name: Setup RSpec
        run: |
          bundle update --bundler
          [ -f Gemfile ] && bundle
      - name: RSpec Report
        run: bundle exec rspec --force-color --format documentation
